-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [long_subtraction]: function definitions
import Aeneas
open Aeneas.Std Result Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- [long_subtraction::sub_borrow]:
   Source: 'src/main.rs', lines 5:0-13:1 -/
def sub_borrow
  (b0 : U8) (src1 : U64) (src2 : U64) (dst : U64) : Result (U8 × U64) := do
  let i ← (↑(UScalar.cast .U64 b0) : Result U64)
  let tmp1 ← (↑(core.num.U64.wrapping_sub src1 i) : Result U64)
  let b1 ← if tmp1 > src1
             then ok 1#u8
             else ok 0#u8
  let tmp2 ← (↑(core.num.U64.wrapping_sub tmp1 src2) : Result U64)
  let b2 ← if tmp2 > tmp1
             then ok 1#u8
             else ok 0#u8
  let i1 ← b1 + b2
  ok (i1, tmp2)

/- [long_subtraction::sub]:
   Source: 'src/main.rs', lines 15:0-21:1 -/
def sub
  (b0 : U8) (src1 : Array U64 4#usize) (src2 : Array U64 4#usize)
  (dst : Array U64 4#usize) :
  Result (U8 × (Array U64 4#usize))
  := do
  let i ← Array.index_usize src1 0#usize
  let i1 ← Array.index_usize src2 0#usize
  let (i2, index_mut_back) ← Array.index_mut_usize dst 0#usize
  let (b1, i3) ← sub_borrow b0 i i1 i2
  let i4 ← Array.index_usize src1 1#usize
  let i5 ← Array.index_usize src2 1#usize
  let dst1 := index_mut_back i3
  let (i6, index_mut_back1) ← Array.index_mut_usize dst1 1#usize
  let (b2, i7) ← sub_borrow b1 i4 i5 i6
  let i8 ← Array.index_usize src1 2#usize
  let i9 ← Array.index_usize src2 2#usize
  let dst2 := index_mut_back1 i7
  let (i10, index_mut_back2) ← Array.index_mut_usize dst2 2#usize
  let (b3, i11) ← sub_borrow b2 i8 i9 i10
  let i12 ← Array.index_usize src1 3#usize
  let i13 ← Array.index_usize src2 3#usize
  let dst3 := index_mut_back2 i11
  let (i14, index_mut_back3) ← Array.index_mut_usize dst3 3#usize
  let (b4, i15) ← sub_borrow b3 i12 i13 i14
  let dst4 := index_mut_back3 i15
  ok (b4, dst4)
